name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-image .
        docker tag my-image ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      id: plan
      run: |
        terraform plan \
          -var "image_tag=${{ github.sha }}" \
          -out=tfplan

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply tfplan
